# Generated by Django 6.1 on 2026-08-18 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("rent", "Сдаю"),
                            ("seek", "Ищу жильё"),
                            ("seek_roommate", "Ищу соседа"),
                        ],
                        max_length=20,
                        verbose_name="Тип объявления",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("room", "Комната"),
                            ("apartment", "Квартира"),
                            ("house", "Дом"),
                            ("bed", "Койко-место"),
                            ("shared", "Совместная аренда"),
                        ],
                        max_length=20,
                        verbose_name="Тип жилья",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "district",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Район"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Адрес"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "budget_min",
                    models.PositiveIntegerField(default=0, verbose_name="Мин. бюджет"),
                ),
                (
                    "budget_max",
                    models.PositiveIntegerField(default=0, verbose_name="Макс. бюджет"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="listings/photos/", verbose_name="Фото"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
