# Generated by Django 6.1 on 2026-08-18 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("match", "Матч"),
                            ("message", "Сообщение"),
                            ("viewing", "Просмотр"),
                            ("system", "Система"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "body",
                    models.TextField(blank=True, default="", verbose_name="Текст"),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(blank=True, null=True, verbose_name="ID объекта"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
    ]
