# Generated by Django 6.1 on 2026-08-18 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Имя"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Мужской"),
                            ("female", "Женский"),
                            ("other", "Другой"),
                        ],
                        max_length=10,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, default="", verbose_name="О себе"),
                ),
                (
                    "role_seeker",
                    models.BooleanField(default=False, verbose_name="Ищу жильё"),
                ),
                (
                    "role_roommate",
                    models.BooleanField(default=False, verbose_name="Ищу соседа"),
                ),
                (
                    "role_landlord",
                    models.BooleanField(default=False, verbose_name="Сдаю жильё"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Город"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Район"
                    ),
                ),
                (
                    "budget_min",
                    models.PositiveIntegerField(default=0, verbose_name="Мин. бюджет"),
                ),
                (
                    "budget_max",
                    models.PositiveIntegerField(default=0, verbose_name="Макс. бюджет"),
                ),
                (
                    "gender_pref",
                    models.CharField(
                        choices=[
                            ("male", "Мужской"),
                            ("female", "Женский"),
                            ("any", "Любой"),
                        ],
                        default="any",
                        max_length=10,
                        verbose_name="Предпочтение по полу",
                    ),
                ),
                (
                    "age_min",
                    models.PositiveIntegerField(
                        default=18, verbose_name="Мин. возраст"
                    ),
                ),
                (
                    "age_max",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Макс. возраст"
                    ),
                ),
                (
                    "smoking",
                    models.CharField(
                        choices=[
                            ("yes", "Да"),
                            ("no", "Нет"),
                            ("indifferent", "Не важно"),
                        ],
                        default="indifferent",
                        max_length=15,
                        verbose_name="Курение",
                    ),
                ),
                (
                    "pets",
                    models.CharField(
                        choices=[
                            ("yes", "Да"),
                            ("no", "Нет"),
                            ("indifferent", "Не важно"),
                        ],
                        default="indifferent",
                        max_length=15,
                        verbose_name="Животные",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("morning", "Утренний"),
                            ("evening", "Вечерний"),
                            ("any", "Любой"),
                        ],
                        default="any",
                        max_length=15,
                        verbose_name="График",
                    ),
                ),
                (
                    "rental_period",
                    models.CharField(
                        choices=[
                            ("short", "Краткосрочно"),
                            ("long", "Долгосрочно"),
                            ("any", "Любой"),
                        ],
                        default="any",
                        max_length=15,
                        verbose_name="Срок аренды",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Предпочтения",
                "verbose_name_plural": "Предпочтения",
            },
        ),
        migrations.CreateModel(
            name="UserPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="users/photos/", verbose_name="Фото"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Главное фото"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото пользователя",
                "verbose_name_plural": "Фото пользователей",
                "ordering": ["order"],
            },
        ),
    ]
