# Generated by Django 6.1 on 2026-08-18 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Swipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("user", "Пользователь"), ("listing", "Объявление")],
                        max_length=10,
                        verbose_name="Тип цели",
                    ),
                ),
                ("target_id", models.UUIDField(verbose_name="ID цели")),
                (
                    "action",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        max_length=10,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Свайп",
                "verbose_name_plural": "Свайпы",
                "ordering": ["-created_at"],
            },
        ),
    ]
