# Generated by Django 6.1 on 2026-08-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="match",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="matches.match",
            ),
        ),
    ]
